/// Flutter icons CareHomeIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CareHomeIcons
///      fonts:
///       - asset: fonts/CareHomeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CareHomeIcons {
  CareHomeIcons._();

  static const _kFontFam = 'CareHomeIcons';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData addb = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData addphoto = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrowdown = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData arrowleft = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData arrowup = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData body = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bodydark = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData checktaskactive = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData commentactive = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData homeactive = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData likeactive = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData likeinactive = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData medicationdark = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData medsicon = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData mooddark = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData moodicon = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData nutrition = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData nutritiondark = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData other = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData otherdark = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData patients = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData patientsactive = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData vitalsdark = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData vitalsicon = const IconData(0xe81e, fontFamily: _kFontFam);
}
